services:
  huggingchat-ui:
    container_name: huggingchat-ui
    image: chat-ui:0.1
    build:
      context: ./chat-ui
      dockerfile: ./Dockerfile
    environment:
      ALLOW_INSECURE_COOKIES: "true"
      INCLUDE_DB: "False"
    volumes:
      - "./.env.local:/app/.env.local"
    ports:
      - "0.0.0.0:53000:3000"
    depends_on:
      - "mongo-biochat-ui"
      - "biocypher-kg"

  mongo-biochat-ui:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "127.0.0.1:57017:27017"
    volumes:
      - "./volumes/mongo/db:/data/db"

  biocypher-kg:
    container_name: drug-kg
    image: biocypher/drug-interactions:latest
    environment:
      NEO4J_dbms_security_auth__enabled: "false"
      NEO4J_dbms_databases_default__to__read__only: "false"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "0.0.0.0:57474:7474"
      - "0.0.0.0:57687:7687"

networks:
  default:
    name: biochat-ui
