version: '3.11'
services:
  huggingchat-ui:
    container_name: biochat-ui
    image: justdnaseq/genie-chatui:latest
    build:
      context: ./chat-ui
      dockerfile: ./Dockerfile
    environment:
      ALLOW_INSECURE_COOKIES: "true"
      INCLUDE_DB: "False"
    volumes:
      - "./.env.local:/app/.env.local"
      - "./chat-ui/.env:/app/.env"
    ports:
      - "0.0.0.0:53000:3000"
    depends_on:
      - "mongo-biochat-kg"
      - "biocypher-kg"
      - "litellm-proxy"

  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    command: '--config proxy_server_config.yaml --detailed_debug'
    volumes:
      - "./proxy.yaml:/app/proxy_server_config.yaml"
    ports:
      - "127.0.0.1:54000:4000" # Map the container port to the host, change the host port if necessary
    env_file:
      - ./.env.proxy # Load local .env file
      - ./.env.redis # Load local .env file
    depends_on:
      - "llm-cache"

  llm-cache:
    image: redis:7.4-alpine
    container_name: llm-cache-redis
    restart: unless-stopped
    command: /bin/sh -c "redis-server --loglevel notice --requirepass $$REDIS_PASSWORD --port $$REDIS_PORT"
    env_file:
      - ./.env.redis
    ports:
      - "127.0.0.1:56379:6379"
    volumes:
      - "./volumes/redis_data:/bitnami/redis/data"

  mongo-biochat-kg:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "127.0.0.1:57017:27017"
    volumes:
      - "./volumes/mongo/db:/data/db"

  biocypher-kg:
    container_name: drug-kg
    image: biocypher/drug-interactions:latest
    environment:
      NEO4J_dbms_security_auth__enabled: "false"
      NEO4J_dbms_databases_default__to__read__only: "false"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
    ports:
      - "0.0.0.0:57474:7474"
      - "0.0.0.0:57687:7687"

networks:
  default:
    name: biochat-ui
