name: drugkg_endpoint
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip:
    - fastapi
    - uvicorn
    - loguru
    - httpx
    - openai
    - just-agents>=0.0.7
    - biochatter>=0.7.3
